import type { Config } from 'tailwindcss';
import containerQueries from '@tailwindcss/container-queries';

const config: Config = {
  content: [
    './src/**/*.tsx',
    './node_modules/rizzui/dist/*.{js,ts,jsx,tsx}',
    './packages/isomorphic-core/src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        inter: ['var(--font-inter)'],
        lexend: ['var(--font-lexend)'],
        'plus-jakarta': ['var(--font-plus-jakarta)'],
      },
      screens: {
        '3xl': '1780px',
        '4xl': '2160px',
      },
      colors: {
        background: 'rgb(var(--background) / <alpha-value>)',
        foreground: 'rgb(var(--foreground) / <alpha-value>)',
        muted: 'rgb(var(--muted) / <alpha-value>)',
        'muted-foreground': 'rgb(var(--muted-foreground) / <alpha-value>)',
        primary: {
          lighter: 'rgb(var(--primary-lighter) / <alpha-value>)',
          DEFAULT: 'rgb(var(--primary-default) / <alpha-value>)',
          dark: 'rgb(var(--primary-dark) / <alpha-value>)',
          foreground: 'rgb(var(--primary-foreground) / <alpha-value>)',
        },
        secondary: {
          lighter: 'rgb(var(--secondary-lighter) / <alpha-value>)',
          DEFAULT: 'rgb(var(--secondary-default) / <alpha-value>)',
          dark: 'rgb(var(--secondary-dark) / <alpha-value>)',
          foreground: 'rgb(var(--secondary-foreground) / <alpha-value>)',
        },
        red: {
          lighter: 'rgb(var(--red-lighter) / <alpha-value>)',
          DEFAULT: 'rgb(var(--red-default) / <alpha-value>)',
          dark: 'rgb(var(--red-dark) / <alpha-value>)',
        },
        orange: {
          lighter: 'rgb(var(--orange-lighter) / <alpha-value>)',
          DEFAULT: 'rgb(var(--orange-default) / <alpha-value>)',
          dark: 'rgb(var(--orange-dark) / <alpha-value>)',
        },
        blue: {
          lighter: 'rgb(var(--blue-lighter) / <alpha-value>)',
          DEFAULT: 'rgb(var(--blue-default) / <alpha-value>)',
          dark: 'rgb(var(--blue-dark) / <alpha-value>)',
        },
        green: {
          lighter: 'rgb(var(--green-lighter) / <alpha-value>)',
          DEFAULT: 'rgb(var(--green-default) / <alpha-value>)',
          dark: 'rgb(var(--green-dark) / <alpha-value>)',
        },
        gray: {
          0: 'rgb(var(--gray-0) / <alpha-value>)',
          50: 'rgb(var(--gray-50) / <alpha-value>)',
          100: 'rgb(var(--gray-100) / <alpha-value>)',
          200: 'rgb(var(--gray-200) / <alpha-value>)',
          300: 'rgb(var(--gray-300) / <alpha-value>)',
          400: 'rgb(var(--gray-400) / <alpha-value>)',
          500: 'rgb(var(--gray-500) / <alpha-value>)',
          600: 'rgb(var(--gray-600) / <alpha-value>)',
          700: 'rgb(var(--gray-700) / <alpha-value>)',
          800: 'rgb(var(--gray-800) / <alpha-value>)',
          900: 'rgb(var(--gray-900) / <alpha-value>)',
          1000: 'rgb(var(--gray-1000) / <alpha-value>)',
        },
        // New colors from the HTML
        'surface-bright': '#f8f9ff',
        'on-primary-fixed-variant': '#0a38ae',
        'surface-container-high': '#dce9ff',
        'error-dim': '#770326',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#ddcdff',
        'on-surface-variant': '#416188',
        'surface-container-low': '#eff4ff',
        'inverse-primary': '#6a89ff',
        'inverse-surface': '#000f21',
        'on-surface': '#0d3459',
        'error-container': '#f76a80',
        'secondary-dim': '#622bcb',
        'on-tertiary-fixed-variant': '#006544',
        'on-tertiary-fixed': '#00452d',
        'secondary-fixed': '#e9ddff',
        'on-primary-fixed': '#001f6e',
        'on-background': '#0d3459',
        'on-secondary-fixed': '#4d00b7',
        'primary-container': '#afbeff',
        'on-tertiary': '#e6ffee',
        'on-error-container': '#68001f',
        'tertiary-fixed-dim': '#58e7ab',
        'surface-dim': '#c4dcff',
        'tertiary-dim': '#005f40',
        'on-secondary-container': '#6029c9',
        'outline': '#5d7da6',
        'on-tertiary-container': '#005a3c',
        'tertiary': '#006d4a',
        'on-primary-container': '#00309e',
        'surface-variant': '#d2e4ff',
        'surface-container-highest': '#d2e4ff',
        'on-error': '#fff7f7',
        'outline-variant': '#94b4e0',
        'tertiary-fixed': '#69f6b8',
        'surface': '#f8f9ff',
        'on-primary': '#faf8ff',
        'tertiary-container': '#69f6b8',
        'surface-tint': '#3355c9',
        'primary-dim': '#2348bc',
        'secondary-container': '#e9ddff',
        'on-secondary-fixed-variant': '#6a37d4',
        'on-secondary': '#fdf7ff',
        'primary-fixed': '#afbeff',
        'surface-container': '#e5eeff',
        'primary-fixed-dim': '#9dafff',
        'inverse-on-surface': '#8e9eb7',
        // Specific colors for the new UI
        'atelier-primary': '#3355c9',
        'atelier-secondary': '#6e3bd8',
        'atelier-error': '#ac3149',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [containerQueries],
};

export default config;
