-- Migration: seed admin_auth table with a placeholder. Replace <bcrypt-hash> with real hash generated by scripts/gen-admin-hash.js

BEGIN;

-- Create admin_auth table if not exists
CREATE TABLE IF NOT EXISTS admin_auth (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  password_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Insert a placeholder entry (replace password_hash value with the one from gen-admin-hash.js)
-- Example:
-- INSERT INTO admin_auth (id, password_hash, created_at)
-- VALUES (gen_random_uuid(), '<bcrypt-hash-here>', now());

COMMIT;
